name: Scheduled RSS Fetch

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  fetch-rss:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Verify current directory and list files
        run: |
          echo "Current directory:"
          pwd
          echo "Listing root directory files:"
          ls -al
          echo "Listing prisma directory files:"
          ls -al prisma

      - name: Generate Prisma Client
        run: npx prisma generate --schema=prisma/schema.prisma

      - name: Start Next.js server
        run: npm run dev &
        env:
          PORT: 3000

      - name: Wait for server to be ready
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:3000/api/rss; then
              echo "Server is ready"
              break
            fi
            echo "Waiting for server to be ready..."
            sleep 1
          done

      - name: Send GET request to RSS endpoint
        run: curl -X GET "http://localhost:3000/api/rss"
